version: "3.5"

networks:
    castle_net:
        external: false

services:
    api:
        build: .
        container_name: castles_api
        networks:
            - castle_net
        volumes:
            - /var/castles:/data
        ports:
            - "${HTTP_PORT}:80"
